name: Generate Task List

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to use for lm-evaluation-harness'
        required: false
        default: 'release-0.4.8'
        type: string

jobs:
  generate-task-list:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r lmeval/tasks/requirements.txt
    
    - name: Generate task list
      run: |
        cd lmeval/tasks
        chmod +x generate_task_list.sh
        ./generate_task_list.sh "${{ github.event.inputs.branch || 'release-0.4.8' }}"
      env:
        PYTHONPATH: ${{ github.workspace }}/lmeval/tasks
    
    - name: Group tasks by dataset
      run: |
        cd lmeval/tasks
        python3 group_tasks_by_dataset.py
    
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add lmeval/tasks/new_task_list.csv lmeval/tasks/dataset_groupings.csv
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update task list and dataset groupings from branch ${{ github.event.inputs.branch || 'release-0.4.8' }}"
          git push
        fi 